spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.0.3:5432/p2p_loan
    username: postgres
    password: 123456

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.p2p.loan.backend.controller

knife4j:
  enable: true
  setting:
    language: zh_cn


web3j:
  url: 'http://172.31.0.3:8545/'
  loan-contract-address: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
  owner-private-key: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'






